services:
  # 1. Spring Boot Backend Web Service via Docker
  - type: web
    name: visitor-ms-backend
    env: docker
    plan: free
    rootDir: backend
    healthCheckPath: /api/visitors
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false

  # 2. React Vite Static Site
  - type: web
    name: visitor-ms-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: visitor-ms-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_GEMINI_API_KEY
        sync: false
